import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <meta name="google-adsense-account" content="ca-pub-5708777381218001"/>
    </head>
      <body suppressHydrationWarning className={inter.className}>{children}</body>
    </html>
  );
}
